[package]
name = "voxel"
version = "0.1.0"
authors = ["serxka <serxka>"]
edition = "2018"

[dependencies]
gl = { path = "src/opengl/" }
glutin = "0.26"
image = "0.23"
log = "0.4"
ron = "0.6"
serde = "1"
simple_logger = "1.11"
ultraviolet = "0.8"
winit = { version = "0.24", features = ["serde"] }
